version: "3"
services:
  ##
  # Reverse Proxy
  ##
  vulpee-proxy:
    image: traefik
    container_name: vulpee-proxy
    command: -c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ##
  # Back-end database
  ##
  vulpee-postgres:
    image: postgres:alpine
    container_name: vulpee-back-end-db
    volumes:
      - vulpee-postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vulpee
      POSTGRES_USER: vulpee
      POSTGRES_PASSWORD: vulpee

  ##
  # Back-end
  ##
  vulpee-back-end-typescript:
    build: ./docker/node
    container_name: vulpee-back-end-typescript
    command: >
      bash -c 'set -euo pipefail \
        && npm install \
        && npm run start:typescript'
    volumes:
      - ../back-end:/app
      - ~/.npmrc:/root/.npmrc
    working_dir: /app

  vulpee-back-end:
    build: ./docker/node
    container_name: vulpee-back-end
    command: >
      bash -c 'set -euo pipefail \
        && npm install \
        && npm run start'
    volumes:
      - ../back-end:/app
      - ~/.npmrc:/root/.npmrc
    working_dir: /app
    depends_on:
      - vulpee-postgres
      - vulpee-back-end-typescript
    labels:
      - "traefik.backend=vulpee-back-end"
      - "traefik.api.frontend.rule=Host:api.vulpee.local"
      - "traefik.client-api.frontend.rule=HostRegexp:{subdomain:[a-z|-]+}.api.vulpee.local"
      - "traefik.docker.network=default"
      - "traefik.api.port=3333"
      - "traefik.client-api.port=3333"

  ##
  # Admin
  ##
  vulpee-admin:
    build: ./docker/node
    container_name: vulpee-admin
    command: >
      bash -c 'set -euo pipefail \
        && npm install \
        && npm run start'
    volumes:
      - ../admin:/app
      - ~/.npmrc:/root/.npmrc
    working_dir: /app
    labels:
      - "traefik.backend=vulpee-admin"
      - "traefik.frontend.rule=Host:app.vulpee.local"
      - "traefik.docker.network=default"
      - "traefik.port=3300"

  ##
  # Storybook
  ##
  vulpee-storybook:
    build: ./docker/node
    container_name: vulpee-storybook
    command: >
      bash -c 'set -euo pipefail \
        && npm install \
        && npm run storybook'
    volumes:
      - ../ui:/app
      - ~/.npmrc:/root/.npmrc
    working_dir: /app
    labels:
      - "traefik.backend=vulpee-storybook"
      - "traefik.frontend.rule=Host:ui.vulpee.local"
      - "traefik.docker.network=default"
      - "traefik.port=3300"

volumes:
  vulpee-postgres:
    driver: "local"

networks:
  default:
    driver: bridge
